### ISSUE TITLE
Drop Python 2 compatability support

### ISSUE THREAD

**Issue by ITAYC0HEN** [CERT-Polska/malduck#4]
All good things should come to an end. 

[![]( https://yt-embed.herokuapp.com/embed?v=aU-dKoFZT0A)](https://www.youtube.com/watch?v=aU-dKoFZT0A)

**Comment by psrok1** [comment]
Support for Python 2 will be dropped in next major release (4.0.0).

Next minor release (3.2.0) will be the last version cross-compatible with Py2.

Cross-compatible code complicates the development process a lot (especially for code that operates mainly on `bytes`) and keeps us from introducing Py3-only things like type hints.

**Comment by nazywam** [comment]
Was this closed by https://github.com/CERT-Polska/malduck/pull/16?
