### ISSUE TITLE
[integrations] question

### ISSUE THREAD

**Issue by doomedraven** [CERT-Polska/malduck#63]
Hello, thanks for nice project. We want to do proper integration to CAPE sandbox, but we need to check many things, and write a lot of stuff to avoid double yara scan, to not store yara twice, etc. Do you have some simple way to use malduck based extractors when you already have yara matched?

would appreciate any help on this
Thanks

**Comment by psrok1** [comment]
Hi @doomedraven!

The extraction part is splitted into two parts:
- `ExtractManager.push_procmem` (https://github.com/CERT-Polska/malduck/blob/master/malduck/extractor/extract_manager.py#L208) tries to detect possible binary types. performs Yara match and does extraction using all possible variations of `buffer->virtual memory` mapping (extract file as PE dump, PE image file etc.). Then the most complete configuration for each family is chosen from these extractions.
- Extraction modules are called using `ProcmemExtractManager.push_procmem` (https://github.com/CERT-Polska/malduck/blob/master/malduck/extractor/extract_manager.py#L301) which gets yara matches from `ExtractManager.push_procmem` as an argument.

So if you already have information about Yara matches from previous stage of processing in CAPE, I would suggest using `ProcmemExtractManager.push_procmem` and provide some dummy `parent` object for callbacks. YaraRulesetMatch can be constructed directly from `yara.Yara.match` object just like here: https://github.com/CERT-Polska/malduck/blob/master/malduck/yara.py#L191

Of course it's not the most elegant solution. If you still want to work on `ExtractManager` level and let malduck to try different combinations of mappings, we need to implement some additional methods.

**Comment by doomedraven** [comment]
hello @psrok1 thank you for the response, im going to try that in a bit and will be back if you don't care to provide a bit of help just in case of need, but this is already good start for me

**Comment by psrok1** [comment]
Sure, just let me know in case of any problems :wink: 

I think it would be nice idea implement a bit more high-level interface that accepts just bytes/file path and optional Yara match, without messing with ProcessMemory and YaraRulesetMatch wrappers. The most close method to that use-case is `push_file` (https://github.com/CERT-Polska/malduck/blob/13bc864e112e9edbaf0652b0f75216b4c5dc9ab6/malduck/extractor/extract_manager.py#L178) but only paths are accepted and we can't pass our own matches there.

**Comment by doomedraven** [comment]
yes that would be a perfect bridge between tools, lets see maybe later when i will get a bit more of spare time i will come with an solution or idea, thank you

**Comment by doomedraven** [comment]
thank you again for fast response/support, i will leave copy here what we have done so far, i guess this isn't the best way to do that, but it works just fine, so maybe other can use this approach to get their tools integrations 

```
import os, tempfile
file_data = open("/opt/CAPEv2/storage/analyses/4//CAPE/c3a47862ba3a2b029dff936637b40916cf0c1e0d2dd2ad4933812576bc2ae3b1", "rb").read()

from lib.cuckoo.common.config import Config
from lib.cuckoo.common.objects import File
from malduck.extractor import ExtractorModules, ExtractManager
from malduck.extractor.extractor import Extractor
from malduck.extractor.loaders import load_modules
from malduck.yara import Yara

cape_name = "citadel" # passed from yara match
cape_config = dict()
process_cfg = Config("processing")

malduck_rules = Yara.__new__(Yara)
malduck_modules = ExtractorModules.__new__(ExtractorModules)
tmp_modules = load_modules(process_cfg.malduck.modules_path)
malduck_modules_names = dict((k.split(".")[-1], v) for k, v in tmp_modules.items())

if cape_name.lower() not in malduck_modules_names:
   return 

ext = ExtractManager.__new__(ExtractManager)
ext.configs = {}
malduck_rules.rules = File.yara_rules["CAPE"]
malduck_modules.rules = malduck_rules
malduck_modules.extractors = Extractor.__subclasses__()
ext.modules = malduck_modules
tmp_file = tempfile.NamedTemporaryFile(delete=False)
tmp_file.write(file_data)
ext.push_file(tmp_file.name)
tmp_file.close()
cape_config[cape_name] = ext.config
del ext
```
