### ISSUE TITLE
Would it be possible to update the pefile version

### ISSUE THREAD

**Issue by LeanVel** [CERT-Polska/malduck#79]
currently malduck depends on pefile 2019 instead of the latest version. Other systems that integrate with malduck have quite some conflict with pefile and cant install malduck

Thanks!

**Comment by psrok1** [comment]
Sure! Actually I have added strict pinning because I was waiting for a patch to be merged (https://github.com/CERT-Polska/malduck/blob/master/malduck/pe.py#L23).

**Comment by psrok1** [comment]
Included in v4.3.0
